name: CI

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Define an environment variable to hold the secret
      - name: Print PRIVATEDATA (will be redacted in logs)
        env:
          PRIVATEDATA: ${{ secrets.PRIVATEDATA }}
        run: |
          echo "Secret: $PRIVATEDATA"
